[project]
name = "bootable-container-image"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "podman>=5.6.0",
    "rich>=14.1.0",
]
